export const LANGUAGES = [
  ["en", "ENGLISH"],
  ["hi", "हिन्दी"],
  ["te", "తెలుగు"],
  ["ta", "தமிழ்"],
  ["es", "ESPAÑOL"],
  ["fr", "FRANÇAIS"],
  ["ar", "العربية"],
  ["zh-CN", "中文"],
  ["ja", "日本語"],
  ["de", "DEUTSCH"],
  ["pt", "PORTUGUÊS"],
  ["ru", "РУССКИЙ"],
  ["ko", "한국어"],
  ["it", "ITALIANO"],
  ["nl", "DUTCH"],
  ["tr", "TÜRKÇE"],
  ["bn", "বাংলা"],
  ["mr", "मराठी"],
  ["gu", "ગુજરાતી"],
  ["kn", "ಕನ್ನಡ"],
  ["ml", "മലയാളം"],
  ["ur", "اردو"],
  ["pa", "ਪੰਜਾਬੀ"],
  ["vi", "TIẾNG VIỆT"],
  ["th", "ไทย"],
  ["id", "BAHASA"],
  ["pl", "POLSKI"],
  ["sv", "SVENSKA"],
  ["el", "ΕΛΛΗΝΙΚΆ"],
  ["he", "עברית"],
];